config/routes.rb
Rails.application.routes.draw do
  root 'site#index'

  post 'check_availability' => 'site#check_availability'

  resources :bookings, only: [:create]
  

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :listing
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def create
  	booking = Booking.create(booking_params)
  	respond_to do |format|
    	format.js
    end
  end

  private

  def booking_params
		params.require(:booking).permit(:customer_name, :plate_number, :time_start, :time_end, :listing_id)
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  def index
  	@cities = Listing.select(:city).distinct
  end

  def check_availability
  	@start_date = create_datetime(params['start-date'], params['start-time'])
  	@end_date = create_datetime(params['end-date'], params['end-time'])
    @hours = (@end_date - @start_date) * 24.hours/ 3600.seconds
  	city = params['city']

  	bookings = Listing.joins('left outer join bookings on listings.id = bookings.listing_id').where("listings.city = ? AND ? < bookings.time_end AND ? > bookings.time_start", city, @start_date, @end_date).group('bookings.listing_id').count

  	not_available = []

  	bookings.each do |location, occupancy|
  		listing = Listing.find(location)
  		not_available << listing.id if occupancy >= listing.available
  	end
		
		@available_locations = Listing.where(:city => city).where.not(id: not_available).order(:price_per_hour)

  	respond_to do |format|
  		if @available_locations.empty?
  			format.js { render :template => "site/unavailable" }
  		else
  			format.js { render :template => "site/available" }
  		end
    end
  end

  private

  def create_datetime(date, time)
  	DateTime.strptime(date+'-'+time, '%m/%d/%Y-%H:%M')
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/create.js.erb
$('#availability-result').html("");
alert("Your parking space has been reserved.\nThank you!");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Book parking</title>
  <meta name="description" content="">
  <meta name="author" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/png" href="images/favicon.png">
  <%= favicon_link_tag 'favicon.png'%>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'skeleton' %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= yield %>

	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js' %>
</body>
</html>

app/views/site/_parking_available.html.erb
<div class="row">
	<div class="twelve columns">
	  <p>Parking is available 
	  	from <span class="quote-start"><%= @start_date.to_time.utc.strftime("%Y-%m-%d %I:%M%p")%></span> to <span class="quote-end"><%= @end_date.to_time.utc.strftime("%Y-%m-%d %I:%M%p")%></span> 
	  	starting from <strong><%=number_to_currency(@available_locations.minimum(:price_per_hour, :unit => "$") * @hours)%><span class="quote-amount"></span></strong>.
	  </p>
	</div>
</div>

<% @available_locations.each do |location| %>
	<div class="row">
		<div class="nine columns">
		  <p><%= location.seller_name %>, <strong><%= "#{location.address}, #{location.city}" %></strong> is available for <strong><%=number_to_currency(location.price_per_hour * @hours, :unit => "$")%><span class="quote-amount"></span></strong>.</p>
		</div>

		<div class="three columns">
			<%= button_to "Book now", bookings_path({ booking: {listing_id: location, time_start: @start_date, time_end: @end_date }}), class: "button-primary", remote: true, method: :post %>
		</div>
	</div>
<% end %>

app/views/site/_parking_unavailable.html.erb
<div class="row">
	<div class="twelve columns">
	   <p>
	   	Parking is not available 
	   	from <span class="quote-start"><%= @start_date.to_time.utc.strftime("%Y-%m-%d %I:%M%p")%></span> to <span class="quote-end"><%= @end_date.to_time.utc.strftime("%Y-%m-%d %I:%M%p")%></span>.
	   </p>
	</div>
</div>

app/views/site/available.js.erb
$('#availability-result').html("<%= j render partial: 'parking_available' %>");

app/views/site/index.html.erb
<div class="container">

  <%= form_tag('/check_availability', remote: true) do %>
    <div class="row">
      <div class="twelve columns">
        <h1>Book parking</h1>
      </div>
    </div>

    <div class="row">
      <div class="six columns">
        Start time:
        <select name="start-time" id="start-time">
          <option value="00:00">12:00am</option>
          <option value="01:00">01:00am</option>
          <option value="02:00">02:00am</option>
          <option value="03:00">03:00am</option>
          <option value="04:00">04:00am</option>
          <option value="05:00">05:00am</option>
          <option value="06:00">06:00am</option>
          <option value="07:00">07:00am</option>
          <option value="08:00">08:00am</option>
          <option value="09:00">09:00am</option>
          <option value="10:00">10:00am</option>
          <option value="11:00">11:00am</option>
          <option value="12:00">12:00pm</option>
          <option value="13:00">01:00pm</option>
          <option value="14:00">02:00pm</option>
          <option value="15:00">03:00pm</option>
          <option value="16:00">04:00pm</option>
          <option value="17:00">05:00pm</option>
          <option value="18:00">06:00pm</option>
          <option value="19:00">07:00pm</option>
          <option value="20:00">08:00pm</option>
          <option value="21:00">09:00pm</option>
          <option value="22:00">10:00pm</option>
          <option value="23:00">11:00pm</option>
        </select>
        <input type="text" name="start-date" id="start-date" class="date">
      </div>
      <div class="six columns">
        End time:
        <select name="end-time" id="end-time">
          <option value="00:00">12:00am</option>
          <option value="01:00" selected>01:00am</option>
          <option value="02:00">02:00am</option>
          <option value="03:00">03:00am</option>
          <option value="04:00">04:00am</option>
          <option value="05:00">05:00am</option>
          <option value="06:00">06:00am</option>
          <option value="07:00">07:00am</option>
          <option value="08:00">08:00am</option>
          <option value="09:00">09:00am</option>
          <option value="10:00">10:00am</option>
          <option value="11:00">11:00am</option>
          <option value="12:00">12:00pm</option>
          <option value="13:00">01:00pm</option>
          <option value="14:00">02:00pm</option>
          <option value="15:00">03:00pm</option>
          <option value="16:00">04:00pm</option>
          <option value="17:00">05:00pm</option>
          <option value="18:00">06:00pm</option>
          <option value="19:00">07:00pm</option>
          <option value="20:00">08:00pm</option>
          <option value="21:00">09:00pm</option>
          <option value="22:00">10:00pm</option>
          <option value="23:00">11:00pm</option>
        </select>
        <input type="text" name="end-date" id="end-date" class="date">
      </div>
    </div>
    <div class="row">
      <div class="six columns">
        City: <%= select_tag "city", options_from_collection_for_select(@cities, :city, :city), prompt: "Select a City" %>
      </div>
    </div>
    <div class="row">
      <div class="twelve columns">
        <%= submit_tag 'Check Availability' %>
      </div>
    </div>
  <% end %>

  <div class="row" id="availability-result"></div>

</div>

app/views/site/unavailable.js.erb
$('#availability-result').html("<%= j render partial: 'parking_unavailable' %>");